### ISSUE TITLE
Exception on Laravel 5.4

### ISSUE THREAD

**Issue by scrapewww** [Codulab/laravel-restricted#1]
I forked and fixed, please check out.
https://github.com/scrapewww/laravel-restricted

**Comment by SeunMatt** [comment]
@scrapewww that's great. But what exception exactly did you fix? Kindly explain it and how we can reproduce it. Then you can create a PR that can be merged into the repo. Thanks 

cc @Godofbrowser

**Comment by Godofbrowser** [comment]
@scrapewww Thanks for Update. There were several undocumented changes that took place between laravel5.3 and 5.4. This is obviously one of them. Kindly create a pull request to the dev branch so we can merge your solution. Thanks once more.

**Comment by scrapewww** [comment]
Sorry for the late reply!

`Fixed FatalThrowableError Exception thrown in Laravel 5.4.

"Call to undefined method Illuminate\Routing\Route::getPath()"`

**Comment by Godofbrowser** [comment]
Merged. Thanks for the fix.
