### ISSUE TITLE
EOL problem

### ISSUE THREAD

**Issue by tradzero** [Codulab/laravel-restricted#4]
https://github.com/Codulab/laravel-restricted/blob/2cdfc53162b345a7e99b676ef4de07ce52bb69da/src/RestrictedServiceProvider.php#L73

I think this line has problem in unix like OS, you should use `'PHP_EOL' ` replace `"\r\n"`,
and in map callback, i guest it can use `trim()` to replace `preg_replace`?

**Comment by tradzero** [comment]
if you want to remove first space , maybe `ltrim()` is more suitable?

**Comment by Godofbrowser** [comment]
Thanks, code will be updated.

**Comment by tradzero** [comment]
please release this version that i can update my composer library. thanks

**Comment by Godofbrowser** [comment]
@tradzero Done. Sorry it delayed.
